function [Aeq_ic,beq_ic] = InitialConditionMatrixAuto(in1)
%InitialConditionMatrixAuto
%    [Aeq_ic,BEQ_IC] = InitialConditionMatrixAuto(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    04-Dec-2023 09:52:38

qic1 = in1(1,:);
qic2 = in1(2,:);
qic3 = in1(3,:);
qic4 = in1(4,:);
qic5 = in1(5,:);
qic6 = in1(6,:);
Aeq_ic = reshape([1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[6,10]);
if nargout > 1
    beq_ic = [qic1;qic2;qic3;qic4;qic5;qic6];
end
