function bcon_eq = Bconfile(in1)
%Bconfile
%    BCON_EQ = Bconfile(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    15-Dec-2023 11:57:25

xic1 = in1(1,:);
xic2 = in1(2,:);
xic3 = in1(3,:);
xic4 = in1(4,:);
bcon_eq = [0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;xic1;xic2;xic3;xic4];
